version: 2.1 # Use v2.1 to enable orb usage.

# The Windows orb gives you everything you
# need to start using the Windows executor.
orbs:
  win: circleci/windows@2.2.0

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "large"
    steps:
      # Commands are run in a Windows
      # virtual machine environment
      - checkout
      - run: 
          name: Download Vcpkg
          command: git clone git@github.com:microsoft/vcpkg.git vcpkg-install
      - run: 
          name: Install Vcpkg
          command: .\vcpkg-install\bootstrap-vcpkg.bat
      - run:
         name: Integrate Vcpkg with MsBuild
         command: .\vcpkg-install\vcpkg.exe integrate install
      - run: 
          name: Build Aleph One
          command: $vswhere_path = if ([Environment]::Is64BitOperatingSystem) 
            {"${Env:Programfiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"} 
            else {"${Env:Programfiles}\Microsoft Visual Studio\Installer\vswhere.exe"};
            $msbuild_path = &$vswhere_path -latest -requires Microsoft.Component.MSBuild -find "MSBuild\**\Bin\MSBuild.exe";
           &$msbuild_path .\Source_Files\AlephOne.Sln /t:"Build" /p:Configuration="Release" /p:Platform=x64; 
          no_output_timeout: 2h

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - build
