name: release-steam-windows

on: [workflow_dispatch, workflow_call]

jobs:
  release-steam-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  

    - name: Restore config.vdf
      env:
        CONFIG_VDF: ${{ secrets.CONFIG_VDF }}
      run: echo $CONFIG_VDF | base64 -di > "./config.vdf"
      shell: bash