name: release-steam-mac-os

on: [workflow_dispatch, workflow_call]

jobs:
  release-steam-mac-os:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Restore config.vdf
      env:
        CONFIG_VDF: ${{ secrets.CONFIG_VDF }}
      run: echo $CONFIG_VDF | base64 --decode > "./config.vdf"