name: release-steam-shim

on: [workflow_dispatch, workflow_call]

jobs:
  release-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
        
    - name: Install Steamworks SDK 1.59
      run: |
        cd Steam &&
        Invoke-WebRequest -Uri "https://partner.steamgames.com/downloads/steamworks_sdk_159.zip" -OutFile "steamworks_sdk.zip" &&
        Expand-Archive -Path "steamworks_sdk.zip" &&
        Move-Item -Path "steamworks_sdk\sdk" -Destination "sdk"
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      
    - name: Build
      run: |
        cd Steam &&
        msbuild SteamShim.sln
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: alephone-steam-shim-windows
        if-no-files-found: error
        path: Steam/x64/**/*.exe