name: release-steam-mac-os

on: [workflow_dispatch, workflow_call]

jobs:
  release-steam-mac-os:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
        
    - name: Install Tools
      run: brew install nasm
      
    - name: Vcpkg Integration
      run: $VCPKG_INSTALLATION_ROOT/vcpkg integrate install
      
    - name: Get Vcpkg current hash
      run: echo "vcpkg_current_hash=$(git -C $VCPKG_INSTALLATION_ROOT rev-parse --short HEAD)" >> $GITHUB_ENV
        
    - name: Restore vcpkg cache for x64
      uses: actions/cache@v4
      with:
        path: vcpkg/installed-x64-osx
        key: ${{runner.os}}-installed-x64-osx-${{env.vcpkg_current_hash}}-${{hashFiles('**/vcpkg.json')}}
        
    - name: Restore vcpkg cache for arm64
      uses: actions/cache@v4
      with:
        path: vcpkg/installed-arm64-osx
        key: ${{runner.os}}-installed-arm64-osx-${{env.vcpkg_current_hash}}-${{hashFiles('**/vcpkg.json')}}
        
    - name: Switch to Xcode 14.3.1
      run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
      
    - name: Install Dependencies
      run: cd vcpkg && ./install-x64-osx.sh && ./install-arm-osx.sh
      
    - name: Bootstrap Steamcmd
      continue-on-error: true #Steamcmd may throw error exit code while bootstrapping that we can ignore, we will see on upload if everything is working fine
      run: |
        mkdir ~/Steam &&
        cp -R vcpkg/installed-x64-osx/x64-osx/tools/steamworks-sdk/ ~/Steam &&
        cd ~/Steam &&
        chmod +x steamcmd.sh &&
        chmod +x steamcmd &&
        ./steamcmd.sh +quit

    - name: Restore config.vdf
      env: 
        CONFIG_VDF: ${{ secrets.CONFIG_VDF }}
      run: echo $CONFIG_VDF | base64 --decode > ~/"Library/Application Support/Steam/config/config.vdf"
        
    - name: Build Steam Marathon
      run: cd PBProjects && xcodebuild -target "Marathon Steam" -target "Classic Marathon Launcher" DEVELOPMENT_TEAM='' CODE_SIGN_IDENTITY='-' CODE_SIGN_STYLE='Automatic' build

    - name: Deploy to Steam
      run: ~/Steam/steamcmd.sh +login alephone_upload +run_app_build ../m1_mac.vdf +quit